# Generated by Django 4.2.6 on 2023-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_menuitem_image_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('g', 'g'), ('units', 'units'), ('other', 'other')], default='other', max_length=10, verbose_name='Units'),
        ),
    ]
